// Generated by CoffeeScript 1.6.3
(function() {
  var Scenario, oWrap;

  oWrap = require("owrap");

  Scenario = (function() {
    function Scenario(__documents) {
      var _this = this;
      this.__documents = __documents;
      this.__resolver = oWrap();
      this.__resolver.on("control:$type", function(obj) {
        var d, document, factory, r, required, _i, _len;
        if (obj.$type !== "factory") {
          return obj;
        }
        factory = _this.__documents.getFactory(obj.name);
        document = factory.create();
        required = obj.options.required;
        for (_i = 0, _len = required.length; _i < _len; _i += 1) {
          r = required[_i];
          d = _this.__documents.getDocument(r);
          document.modify(d);
        }
        return document.get();
      });
    }

    Scenario.prototype.resolve = function(scenarioObject) {
      return this.__resolver.resolve(scenarioObject);
    };

    return Scenario;

  })();

  module.exports = Scenario;

}).call(this);
